version: '3.4'

services:
  nginx:
    container_name: ${CONTAINER_NAME_NGINX}
    restart: always
    image: nginx:1.21.5
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./www/:/usr/share/nginx/html/ # webroot files.
